# Basic Opencv

In [ ]:
import cv2
import numpy as np

In [ ]:
# Loading color image in grayscale
img1 = cv2.imread("img/beach.jpg",0)

# Loading an color image in rgb
img2 = cv2.imread("img/beach.jpg",1)

# Loading an color image in rgb
img3 = cv2.imread("img/beach.jpg",-1)

### Displaying an image

In [ ]:
cv2.imshow("Grayscale image",img1)
#cv2.imshow("RGB image",img2)
cv2.imshow("RGB image",img3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.namedWindow("image",cv2.WINDOW_NORMAL)
cv2.imshow("image",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Writting or Saving an image

In [ ]:
cv2.imwrite("Nature_scene.png",img1)

### Using Matplotlib

In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

img = cv2.imread("img/beach.jpg",1)
plt.imshow(img,cmap="gray",interpolation="bicubic")
plt.xticks([]), plt.yticks([])
plt.show()

### Drawing line

In [1]:
import cv2
import numpy as np

# Create a black image
img = np.zeros((512,512,3),np.uint8)

# Draw a diagonal blue line with thickness of 5 px
# cv2.line(image,starting cordinates,ending cordinates, color, thickness)
img = cv2.line(img,(0,0),(200,200),(0,255,0),5)
cv2.imshow("Drawing",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Drawing Rectangle

In [2]:
# cv2.rectangle(image,starting vertex,opposite vertex,color,thickness)
img = cv2.rectangle(img,(300,100),(510,128),(0,255,0),3)
cv2.imshow("Line",img)
cv2.waitKey(0)
cv2.destroyAllWindows()



### Drawing a circle

In [3]:
#cv2.circle(image,center,radius,color,fill)
img = cv2.circle(img,(447,63),63,(0,0,255),-1)
cv2.imshow("Line",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Drawing Ellipse

In [4]:
#
img = cv2.ellipse(img,(256,256),(100,50),0,0,180,255,-1)
cv2.imshow("Line", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Drawing Polygon

In [5]:
pts = np.array([[10,5],[20,30],[70,20],[50,10]],np.int32)
pts = pts.reshape((-1,1,2))
img = cv2.polylines(img,[pts],True,(0,255,255))
cv2.imshow("Line",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Adding text to image

In [8]:
# cv2.putText(image,"Text to Display",bottom left starting point, Font, Font Size, Color, Thickness)

font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(img,"OpenCV",(10,500),font,4,(255,255,255),2,cv2.LINE_AA)
cv2.imshow("Line",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Properties of image


In [10]:
import cv2
import numpy as np

# Loading an color image
image = cv2.imread("img/beach.jpg")
print(image.shape)

(638, 1141, 3)


### Total Pixels

In [11]:
print(image.size)

2183874


### Datatype

In [12]:
print(image.dtype)

uint8


### Image Addition

In [13]:
import cv2
import numpy as np
# Create a matrix of ones, then multiply it by a scaler of 150 
# This gives a matrix with same dimesions of our image with all values being 150
image = cv2.imread("img/beach.jpg")
M = np.ones(image.shape,dtype="uint8")*150
print(M)

# We use this to add this matrix M, to our image
# Notice the increase in brightness
added = cv2.add(image,M)
cv2.imshow("Added",added)
cv2.waitKey(0)

# Likewise we can also substract
# Notice the decrease in brightness
subtracted = cv2.subtract(image,M)
cv2.imshow("subtracted",subtracted)

cv2.waitKey(0)
cv2.destroyAllWindows()



[[[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 ...

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]]


### Image Blending

In [22]:
img1 = cv2.imread('img/hd5.jpg')
img2 = cv2.imread('img/hd2.jpg')

blend = cv2.addWeighted(img1,0.7,img2,0.3,0)

cv2.imshow('Blended',blend)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
img1.shape,img2.shape

((720, 1280, 3), (720, 1280, 3))

### Bitwise Operations

In [37]:
img1 = cv2.imread("img/hd5.jpg")
img2 = cv2.imread("img/hot.png")

# I want to put logo on top-left corner, so I create a ROI
rows,cols,channels = img2.shape
roi = img1[0:rows,0:cols]

# Now create a mask of logo and create its inverse mask also
img2gray = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
ret, mask = cv2.threshold(img2gray,10,255,cv2.THRESH_BINARY)
mask_inv = cv2.bitwise_not(mask)

# now black-out the area of logo in ROI
img1_bg = cv2.bitwise_and(roi,roi,mask=mask_inv)

# Take only region of logo from logo image
img2_fg = cv2.bitwise_and(img2,img2,mask=mask)

# put logo in ROI and modify the main image 
dst = cv2.add(img1_bg,img2_fg)
img1[0:rows,0:cols] = dst

cv2.imshow("res",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()